export const LANG = {
  de: {
    tagline: 'Gutes Essen · Gute Menschen · Gute Begegnungen',
    btn_guided: 'Empfehlung erhalten',
    btn_direct: 'Ort direkt suchen',
    no_signup: 'Ohne Anmeldung · Komplett kostenlos',
    preview_label: 'Kursbeispiel',
    features_title: 'Warum Manna?',
    howto_title: 'Zwei Wege zum Start',
    howto_guided: 'Empfehlung',
    howto_direct: 'Direkt suchen',
    step_city: 'SCHRITT 1 / 6',
    city_title: 'Wo trefft ihr euch?',
    city_sub: 'Wähle deine Stadt',
    step_location: 'SCHRITT 2 / 6',
    location_title: 'Welches Viertel?',
    location_sub: 'Wähle einen Bereich',
    step_occasion: 'SCHRITT 3 / 6',
    occasion_title: 'Mit wem gehst du?',
    occasions: ['Date', 'Freunde', 'Familie', 'Business'],
    occasion_descs: ['Mit dem Partner', 'Mit Freunden', 'Familientreffen', 'Geschäftstreffen'],
    step_course: 'SCHRITT 4 / 6',
    course_title: 'Wohin möchtet ihr?',
    course_sub: 'Wähle die Reihenfolge',
    course_btn: (n) => `${n} Ort${n > 1 ? 'e' : ''} planen →`,
    course_hint: 'In dieser Reihenfolge empfehlen wir euren Abend',
    step_budget: 'SCHRITT 5 / 6',
    budget_title: 'Wie viel möchtet ihr ausgeben?',
    budget_sub: 'Geschätztes Budget pro Person',
    budgets: ['Günstig', 'Mittel', 'Besonders', 'Egal'],
    budget_descs: ['unter 15€', '15–40€', 'über 40€', 'Alle Preise'],
    step_cuisine: 'SCHRITT 6 / 6',
    cuisine_title: 'Was für eine Küche?',
    sort_rating: 'Bewertung',
    sort_reviews: 'Rezensionen',
    sort_distance: 'Entfernung',
    walk: 'zu Fuß',
    loading_restaurant: 'Suche Restaurants...',
    loading_cafe: 'Suche Cafés...',
    loading_bar: 'Suche Bars...',
    no_results: 'Keine Ergebnisse gefunden',
    course_done: 'Tour fertig!',
    share_whatsapp: 'Per WhatsApp teilen',
    copy_link: 'Link kopieren',
    link_copied: 'Link kopiert! ✓',
    new_course: 'Neue Tour planen →',
    back: '← Zurück',
    back_home: '← Startseite',
    subway_hint: 'Hier aussteigen',
    direct_title: 'Suche deinen Ort',
    direct_sub: 'Restaurant, Café oder Bar eingeben',
    search_btn: 'Suchen',
    nearby_find: 'Was soll in der Nähe gesucht werden?',
    re_search: '← Erneut suchen',
    map_btn: 'Karte',
  },
  en: {
    tagline: 'Good Food · Good People · Good Meetings',
    btn_guided: 'Get Recommendations',
    btn_direct: 'Search a Place Directly',
    no_signup: 'No signup needed · Completely free',
    preview_label: 'Course Example',
    features_title: 'Why Manna?',
    howto_title: 'Two ways to start',
    howto_guided: 'Recommendations',
    howto_direct: 'Direct Search',
    step_city: 'STEP 1 / 6',
    city_title: 'Where are you meeting?',
    city_sub: 'Choose your city',
    step_location: 'STEP 2 / 6',
    location_title: 'Which neighborhood?',
    location_sub: 'Choose an area',
    step_occasion: 'STEP 3 / 6',
    occasion_title: 'Who are you going with?',
    occasions: ['Date', 'Friends', 'Family', 'Business'],
    occasion_descs: ['With partner', 'With friends', 'Family gathering', 'Business meeting'],
    step_course: 'STEP 4 / 6',
    course_title: 'Where do you want to go?',
    course_sub: 'Select in order',
    course_btn: (n) => `Plan ${n} place${n > 1 ? 's' : ''} →`,
    course_hint: "We'll recommend your evening in this order",
    step_budget: 'STEP 5 / 6',
    budget_title: "What's your budget?",
    budget_sub: 'Estimated budget per person',
    budgets: ['Budget', 'Moderate', 'Special', 'Any'],
    budget_descs: ['Under €15', '€15–40', 'Over €40', 'All prices'],
    step_cuisine: 'STEP 6 / 6',
    cuisine_title: 'What kind of cuisine?',
    sort_rating: 'Rating',
    sort_reviews: 'Reviews',
    sort_distance: 'Distance',
    walk: 'walk',
    loading_restaurant: 'Finding restaurants...',
    loading_cafe: 'Finding cafés...',
    loading_bar: 'Finding bars...',
    no_results: 'No results found',
    course_done: 'Tour complete!',
    share_whatsapp: 'Share via WhatsApp',
    copy_link: 'Copy link',
    link_copied: 'Link copied! ✓',
    new_course: 'Plan new tour →',
    back: '← Back',
    back_home: '← Home',
    subway_hint: 'Get off here',
    direct_title: 'Search your place',
    direct_sub: 'Enter a restaurant, café or bar',
    search_btn: 'Search',
    nearby_find: 'What to find nearby?',
    re_search: '← Search again',
    map_btn: 'Map',
  }
}
